const type = {
    SET_ALL_PASSENGERS: 'SET_ALL_PASSENGERS',
    SET_PASSENGER: 'SET_PASSENGER',
    SET_FLIGHT_PASSENGER: 'SET_FLIGHT_PASSENGER',
    SET_PASSENGER_FLIGHTS: 'SET_PASSENGER_FLIGHTS',
}

export default type;