const type = {
    AUTH_CLEAR_ERRORS: 'AUTH_CLEARE_ERRORS',
    AUTH_SET_ERROR: 'AUTH_SET_ERROR',
    AUTH_SET_USER: 'AUTH_SET_USER',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_RESET_STATE: 'AUTH_RESET_STATE',
    AUTH_SET_PASSENGER: 'AUTH_SET_PASSENGER',
}

export default type;